---
- name: Enable Fractional Scaling
  hosts: all
  tasks:
  - name: Update Gnome settings
    shell:
      cmd: "gsettings set org.gnome.mutter experimental-features \"['scale-monitor-framebuffer']\""