---
- name: Install DotNet Core 8.0 SDK
  hosts: all
  tasks:

  - name: DNF Update
    include_tasks: ../tasks/dnf-update.yml

  - name: Install DotNet Core 8
    become: yes
    ansible.builtin.dnf:
      name:
      - dotnet-sdk-8.0
