---
- name: Configure Python Development Environment
  hosts: all
  vars:
    shell_user: fvcg
  tasks:
  - name: Refresh DNF repositories
    become: yes
    ansible.builtin.dnf:
      update_cache: yes  

  - name: Install Python pre-requisites
    become: yes
    ansible.builtin.dnf:
      name:
      - zlib-devel
      - python3-pip
      - direnv
      - openssl-devel
      - readline-devel 
      - bzip2-devel
      - sqlite-devel
      - python3-gpg
      - postgresql-devel
      - cyrus-sasl-devel
      - python3-devel
      - openldap-devel

  - name: Git checkout pyenv
    ansible.builtin.git:
      repo: 'https://github.com/pyenv/pyenv.git'
      dest: "/home/{{ shell_user }}/.pyenv"

  - name: Git checkout pyenv plugin -> pyenv-virtualenv
    ansible.builtin.git:
      repo: 'https://github.com/pyenv/pyenv-virtualenv.git'
      dest: "/home/{{ shell_user }}/.pyenv/plugins/pyenv-virtualenv"

  - name: Git checkout pyenv plugin -> pyenv-doctor
    ansible.builtin.git:
      repo: 'https://github.com/pyenv/pyenv-doctor.git'
      dest: "/home/{{ shell_user }}/.pyenv/plugins/pyenv-doctor"

  - name: Copy custom pyenv config file
    copy:
      src: ../../files/config/shell/.pyenvrc
      dest: "/home/{{ shell_user }}"
      owner: "{{ shell_user }}"
      group: "{{ shell_user }}"
      mode: g=r,o=r

  - name: Config pyenv loading
    ansible.builtin.lineinfile:
      path: "/home/{{ shell_user }}/.profile"
      line: 'source $HOME/.pyenvrc'
      create: yes  

  # - name: Update alternatives python3 -> python
  #   become: yes
  #   shell:
  #     cmd: update-alternatives --install /usr/bin/python python /usr/bin/python3 1

  # - name: Update alternatives pip3 -> pip
  #   become: yes
  #   shell:
  #     cmd: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

  - name: Install virtualenv
    shell:
      cmd: pip install --user virtualenv
