---
- name: Install Common Applications
  hosts: all
  tasks:
  - name: Update Software Sources
    include_tasks: ../tasks/dnf-update.yml

  - name: Add VS Code Key
    become: yes
    ansible.builtin.rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc

  - name: Install Visual Studio Code rpm repository
    become: true
    ansible.builtin.yum_repository:
      name: visual-studio-code
      description: Visual Studio Code Repository
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgcheck: true
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  - name: Update Software Sources
    include_tasks: ../tasks/dnf-update.yml

  - name: Install DNF Applications
    become: yes
    ansible.builtin.dnf:
      name:
      - neofetch
      - htop
      - chromium
      - gh
      - code
      - tilix
      - gnome-tweaks
      - gnome-extensions-app
      - openh264

