---
- name: Install and configure Docker
  hosts: all
  vars:
    docker_user: fvcg
  tasks:
  - name: APT Update
    include: ../tasks/apt-update.yml

  - name: Install pre-requisites
    include: ../tasks/install-prerequisites.yml
    
  - name: Add an Apt signing key, uses whichever key is at the URL
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository into sources list
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: APT Update
    include: ../tasks/apt-update.yml

  - name: Install Docker CE
    become: yes
    apt:
      pkg: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

  - name: Add docker group
    become: yes
    group:
      name: docker
      
  - name: Add user into Docker group
    become: yes
    user:
      name: "{{ docker_user }}"
      groups: docker
      append: yes
