---
- name: Install DotNet Core 3.1 SDK
  hosts: all
  tasks:

  - name: Install Microsoft Repository
    become: yes
    apt:
      deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
  
  - name: APT Update
    include: ../tasks/apt-update.yml
      
  - name: Install DotNet Core 3.1
    become: yes
    apt:
      pkg:
      - dotnet-sdk-3.1

