---
- name: Install Common Applications
  hosts: all
  tasks:
  - name: Update Software Sources
    include: ../tasks/apt-update.yml
      
  - name: Install APT Applications
    become: yes
    apt:
      pkg:
      - curl
      - wget
      - htop
      - chromium-browser
      - gnome-tweaks
      - tilix
      - zip
