---
- name: Install Zulu 11
  hosts: all
  vars:
    default_user: fvcg
  tasks:

  - name: Add Zulu APT Keys
    become: yes
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: "0xB1998361219BD9C9"
      state: present

  - name: Add Zulu repository
    become: yes
    apt_repository:
      repo: deb http://repos.azulsystems.com/ubuntu stable main
      state: present

  - name: APT Update
    include: ../tasks/apt-update.yml
      
  - name: Install Zulu JDK 11
    become: yes
    apt:
      pkg:
      - zulu-11
